CREATE ROLE health SUPERUSER CREATEDB CREATEROLE NOINHERIT LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'healthpw';

CREATE DATABASE health_maindb;
GRANT ALL PRIVILEGES ON DATABASE health_maindb TO health;

CREATE DATABASE health_testdb;
GRANT ALL PRIVILEGES ON DATABASE health_testdb TO health;