version: "3.9"

services:
  main-db:
    container_name: health_maindb
    image: postgres:latest
    restart: 'always'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - "5432:5432"
  app:
    container_name: hsapp
    depends_on:
      - main-db
    restart: 'always'
    image: sanmoskalenko/hsapp:latest
    environment:
      - DATABASE_URL=main-db
      - DATABASE_PORT=5432
      - USERNAME=health
      - PASSWORD=healthpw
      - WEBSERVER_PORT=3000
    ports:
      - "3000:3000"