---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: default
spec:
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: postgresql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb-config
data:
  init.sql: |
    CREATE ROLE health SUPERUSER CREATEDB CREATEROLE NOINHERIT LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'healthpw';
    CREATE DATABASE health_maindb;
    GRANT ALL PRIVILEGES ON DATABASE health_maindb TO health;
    CREATE DATABASE health_testdb;
    GRANT ALL PRIVILEGES ON DATABASE health_testdb TO health;
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: default
  labels:
    app: postgresql
spec:
  serviceName: postgresql-service
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      volumes:
        - name: init-script
          configMap:
            name: postgresql-initdb-config
      containers:
        - name: postgresql
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: postgrespw
            - name: POSTGRES_USER
              value: postgres
          ports:
            - containerPort: 5432
              protocol: TCP     
          volumeMounts:
              - name: init-script
                mountPath: /docker-entrypoint-initdb.d        
  volumeClaimTemplates:
  - metadata:
      name: postgresql-pvclaim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi