name: Clojure CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: lein deps
      
    - name: Run unit tests
      run: lein test server.health.patient.api.v1-test
    
    - name: build 
      run: |
        cd devops/docker && docker-compose up -d --build

    - name: Run all tests  
      run: | 
        cd devops/docker && docker-compose run app lein test 
